client:
  # domain: 域名配置，默认是 []，表示运行时自动获取域名。
  # 可配置特定域名，如下：
  # 程序会先用第一个域名，如果第一个域名重试n次失败，则换下一个域名重试，以此类推。
  domain:
    - 18comic.vip
    - jm-comic2.org
  postman:
    meta_data:
      # proxies: 代理配置，默认是 null，表示不使用代理。
      # 以下的写法都可以:
      # proxies: clash
      # proxies: v2ray
      # proxies: 127.0.0.1:7890
      # proxies:
      #   http: http://127.0.0.1:7890
      #   https: https://127.0.0.1:7890
      proxies: clash

      # cookies: 帐号配置，默认是 null，表示未登录状态访问JM。
      # 禁漫的大部分本子，下载是不需要登录的；少部分敏感题材需要登录才能看。
      # 如果你希望以登录状态下载本子，最简单的方式是配置一下浏览器的cookies，
      # 不用全部cookies，只要那个叫 AVS 就行。
      # cookies:
      # AVS: qkwehjjasdowqeq # 这个值是乱打的，不能用

# 下载配置
download:
  # 如果要下载的文件在磁盘上已存在，不用再下一遍了吧？
  cache: true
  image:
    decode: true # JM的原图是混淆过的，要不要还原？
    suffix: .jpg # 把图片都转为.jpg格式
  threading:
    # batch_count: 章节的批量下载图片线程数
    # 数值大，下得快，配置要求高，对禁漫压力大
    # 数值小，下得慢，配置要求低，对禁漫压力小
    # PS: 禁漫网页一般是一次请求50张图
    batch_count: 30

# 文件夹规则配置，决定图片文件存放在你的电脑上的哪个文件夹
dir_rule:
  # base_dir: 根目录。
  base_dir: Z:\MyData\小秘密\爬w站2\xia
    # rule: 规则dsl。
    # 本项只建议了解编程的朋友定制，实现在这个类: jmcomic.jm_option.DirRule
    # 写法:
    # 1. 以'Bd'开头，表示根目录
    # 2. 文件夹每增加一层，使用'_'区隔
    # 3. 文件夹名字表示为 Pxxx/Ayyy，意思是 JmPhotoDetail.xxx / JmAlbumDetail的.yyy。xxx和yyy可以写什么需要看源码。
    # 下面是示例，表示使用禁漫网站的默认下载方式 [根目录 / 本子id / 章节序号 / 图片文件]
    # rule: Bd_Aid_Pindex

    # 默认规则是: 根目录 / 章节标题 / 图片文件
    # rule: Bd_Ptitle